init:
    $ bybd3 = "moimod/zvuki/bybd3.mp3"
    $ dojdvdome = "moimod//zvuki/dojdvdome.mp3"
    $ dojd = "moimod/zvuki/dojd.mp3"
    $ praznik = "moimod/zvuki/praznik.mp3"

    image bg blur = "moimod/images/blur.jpg"
    image bg garblur = "moimod/images/garblur.jpg"
    image bg lift = "moimod/images/lift.jpg"
    image bg darksov = "moimod/images/darksov.jpg"
    image bg dom = "moimod/images/dom.jpg"
    image bg les = "moimod/images/les1.jpg"
    image bg postr = "moimod/images/postr.jpg"
    image bg spitzh = "moimod/images/spitzh.jpg"
    image bg lodki = "moimod/images/lodki.jpg"
    image bg posl = "moimod/images/posl.jpg"
    image bg posl2 = "moimod/images/posl2.jpg"
    image bg domzh = "moimod/images/domzh.jpg"
    image bg zhenya = "moimod/images/zhenya.png"

    image bg tanetz = "moimod/images/tanetz.jpg"
    image bg zhsidit = "moimod/images/zhsidit.jpg"
    image bg lesrain = "moimod/images/lesrain.jpg"
    image bg librain = "moimod/images/librain.jpg"
    image bg libafrain = "moimod/images/libafrain.jpg"
    image bg libnight = "moimod/images/libnight.jpg"
    image bg squarerain = "moimod/images/squarerain.jpg"